"""username

Revision ID: 8d3dfb9b068d
Revises: cef7a0c4ee57
Create Date: 2023-09-16 12:01:23.684379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3dfb9b068d'
down_revision: Union[str, None] = 'cef7a0c4ee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tg_User', 'username_test',
                    new_column_name='username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tg_User', 'username',
                    new_column_name='username_test')
    # ### end Alembic commands ###
