"""unic user

Revision ID: b6d495efc3ed
Revises: 6e20933e9ec0
Create Date: 2023-09-13 16:13:17.989405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d495efc3ed'
down_revision: Union[str, None] = '6e20933e9ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_first_name_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_first_name_key', 'User', ['first_name'])
    # ### end Alembic commands ###
