"""t2

Revision ID: cef7a0c4ee57
Revises: 41f7c9a051d0
Create Date: 2023-09-16 10:28:50.395491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef7a0c4ee57'
down_revision: Union[str, None] = '41f7c9a051d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tg_User', 'username',
                    new_column_name='username_test')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tg_User', 'username_test',
                    new_column_name='username')
    # ### end Alembic commands ###
